### PR TITLE
feat: improve error message if response is unexpected

### PR DESCRIPTION
**Pull request by snakeru**

### CODE REVIEW

**Comment by jpgorganizer** [comment]
@snakeru 
I've got the following output from a user

```
Logging into authentication system...
Logged in auth_token=(xxxxxxx)
get locations

Traceback (most recent call last):
File "apitest.py", line 77, in <module>
assert r.status_code == 200, format(r)
AssertionError: https://api.smart.gardena.dev/v1/locations
403 Forbidden
Content-Type: application/json
Content-Length: 23
Connection: keep-alive
Date: Tue, 02 Jun 2020 18:41:07 GMT
x-amzn-RequestId: a2xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
x-amzn-ErrorType: ForbiddenException
x-amz-apigw-id: Ngxxxxxxxxxxxxx=
X-Cache: Error from cloudfront
Via: 1.1 d7147e532e5cf73689fcb39fa760bcf3.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: ZRH50-C1
X-Amz-Cf-Id: 7Qxxxxxxxxxxx_xxxxxxxxx-xxxxxxxxxxxxxxxxxx_xx-xxxxxxxx==

{"message":"Forbidden"}
```

**Comment by jpgorganizer** [comment]
@snakeru 
as mentioned by you, this script was written by yourself. For me this script is very helpful. If one of the users of my iobroker adapter for Gardena has problems, which I can't reproduce, I ask him to run this script. In 9 of 10 times the problem have been wrong login data :-)

Some questions:
- wouldn't it be a good idea to have the script downloadable at a Gardena website as a file? Then it would be under your control.
- or can I let the script here in github? 
  if yes, maybe you should add some copyright notice to it (if you like, then please send a PR)
  if not, then I will delete it from the repository 

Regards,
jpgorganizer

**Comment by snakeru** [comment]
If I understand correctly, then this script was published simply embedded into the README. I personally have no problem with it being extracted and hosted on github (or wherever) by anyone, it was, after all, designed specifically with this idea in mind - that people will reuse it for their own purposes.

That said, it might still be a good idea to host it in some "official repo" and link to it from the readme. My proposal therefore would be that you leave it be for the time being and I'll try to find out if we have an official repo.

Or may be even we'll just slap a GPL on top of it and just link to your repo - we'll see.

**Comment by snakeru** [comment]
Hi @jpgorganizer. Would GPL3 work for you? If yes - I'll send you a PR that just adds these headers and you'll just keep these scripts in your repo. As said already - even now this is totally not a problem, but I understand that you'd prefer to have this topic covered.

**Comment by jpgorganizer** [comment]
Hi @snakeru 

yes GPL3 is fine for me, but you can use every licence you like. 
Pls send a PR.

I'm using this script just for testing if the API is generally working. And I ask users of my implementation in case of errors to test with this script.  It's a test if my implementation has a problem or the interface / login data.
Just a little bit statistic: I've got feedback like *"Oh sorry, I've used the wrong username/password/API key"* from 13 users in May 2020. And all of them wrote first *"There must be an error in your implementation. I can't login"*. If I would start searching for errors every time, I couldn't do something else. :-)


There is a Readme availble - in english and german (because most (all?) users of my ioBroker implementation are german speaking people).  Maybe you like to add something there too. I'm sure that would be ok too.

And many thanks for your support.

--------

 If you like you can have a look at my ioBroker adapter for the API: https://github.com/jpgorganizer/ioBroker.smartgarden

**Pull request merged**
